# Generated by Django 2.0 on 2018-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181113_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FN', 'fun'), ('RX', 'relax'), ('EX', 'experience'), ('SI', 'sights')], default='FN', max_length=20),
        ),
    ]
