# Generated by Django 2.1.3 on 2018-12-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181202_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrun',
            options={'ordering': ['date', 'time']},
        ),
    ]
