# Generated by Django 2.1.3 on 2018-12-04 17:29

from django.db import migrations
import explorea.events.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=explorea.events.models.main_image_url),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=explorea.events.models.thumbnail_image_url),
        ),
    ]
